// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";

import type { InferInsertModel, InferSelectModel } from "kitcn/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

export const api = {
  builds: {
    create: createApiLeaf<"mutation", typeof import("../functions/builds").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/builds").create>("builds:create"), { type: "mutation" }),
    get: createApiLeaf<"query", typeof import("../functions/builds").get>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/builds").get>("builds:get"), { type: "query" }),
    resolve: createApiLeaf<"action", typeof import("../functions/builds").resolve>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/builds").resolve>("builds:resolve"), { type: "action" }),
  },
  economy: {
    itemHistory: createApiLeaf<"query", typeof import("../functions/economy").itemHistory>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/economy").itemHistory>("economy:itemHistory"), { type: "query" }),
    movers: createApiLeaf<"query", typeof import("../functions/economy").movers>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/economy").movers>("economy:movers"), { type: "query" }),
    overview: createApiLeaf<"query", typeof import("../functions/economy").overview>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/economy").overview>("economy:overview"), { type: "query" }),
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
