// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";

import type { InferInsertModel, InferSelectModel } from "kitcn/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

export const api = {
  builds: {
    create: createApiLeaf<"mutation", typeof import("../functions/builds").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/builds").create>("builds:create"), { type: "mutation" }),
    createSaved: createApiLeaf<"mutation", typeof import("../functions/builds").createSaved>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/builds").createSaved>("builds:createSaved"), { auth: "required", type: "mutation" }),
    get: createApiLeaf<"query", typeof import("../functions/builds").get>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/builds").get>("builds:get"), { type: "query" }),
    resolve: createApiLeaf<"action", typeof import("../functions/builds").resolve>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/builds").resolve>("builds:resolve"), { type: "action" }),
  },
  economy: {
    itemHistory: createApiLeaf<"query", typeof import("../functions/economy").itemHistory>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/economy").itemHistory>("economy:itemHistory"), { type: "query" }),
    movers: createApiLeaf<"query", typeof import("../functions/economy").movers>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/economy").movers>("economy:movers"), { type: "query" }),
    overview: createApiLeaf<"query", typeof import("../functions/economy").overview>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/economy").overview>("economy:overview"), { type: "query" }),
  },
  patchStore: {
    latest: createApiLeaf<"query", typeof import("../functions/patchStore").latest>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/patchStore").latest>("patchStore:latest"), { type: "query" }),
    post: createApiLeaf<"query", typeof import("../functions/patchStore").post>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/patchStore").post>("patchStore:post"), { type: "query" }),
  },
  profiles: {
    complete: createApiLeaf<"mutation", typeof import("../functions/profiles").complete>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/profiles").complete>("profiles:complete"), { auth: "required", type: "mutation" }),
    me: createApiLeaf<"query", typeof import("../functions/profiles").me>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/profiles").me>("profiles:me"), { auth: "required", type: "query" }),
  },
  savedBuilds: {
    list: createApiLeaf<"query", typeof import("../functions/savedBuilds").list>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/savedBuilds").list>("savedBuilds:list"), { auth: "required", type: "query" }),
    set: createApiLeaf<"mutation", typeof import("../functions/savedBuilds").set>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/savedBuilds").set>("savedBuilds:set"), { auth: "required", type: "mutation" }),
    status: createApiLeaf<"query", typeof import("../functions/savedBuilds").status>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/savedBuilds").status>("savedBuilds:status"), { auth: "required", type: "query" }),
  },
  watchlist: {
    list: createApiLeaf<"query", typeof import("../functions/watchlist").list>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/watchlist").list>("watchlist:list"), { auth: "required", type: "query" }),
    merge: createApiLeaf<"mutation", typeof import("../functions/watchlist").merge>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/watchlist").merge>("watchlist:merge"), { auth: "required", type: "mutation" }),
    set: createApiLeaf<"mutation", typeof import("../functions/watchlist").set>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/watchlist").set>("watchlist:set"), { auth: "required", type: "mutation" }),
  },
  xStore: {
    latest: createApiLeaf<"query", typeof import("../functions/xStore").latest>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/xStore").latest>("xStore:latest"), { type: "query" }),
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
