/* Shared class strings for the item viewer and its nested jewel/augment
   popovers. Complex textures remain named Tailwind utilities in styles.css. */
export const itemCard =
  "[--item-color:var(--color-item-normal)] [--equipment-modifier-font-size:15px] [--equipment-line-height:1.65] [--equipment-line-gap:3px] [--inspection-width:390px] [--inspection-accent:var(--item-color)] [--inspection-border:color-mix(in_oklch,var(--item-color)_45%,var(--color-rule))] [--inspection-padding:0px] data-[rarity=RARE]:[--item-color:var(--color-item-rare)] data-[rarity=UNIQUE]:[--item-color:var(--color-item-unique)] data-[rarity=MAGIC]:[--item-color:var(--color-item-magic)] data-[augment-replaced=true]:invisible data-[augment-replaced=true]:pointer-events-none max-sm:[--equipment-modifier-font-size:14px]"

export const socket =
  "flex min-w-0 aspect-square items-center justify-center rounded-full border-2 border-augment-socket bg-paper p-[8%] shadow-socket max-sm:border [&>img]:pointer-events-none [&>img]:block [&>img]:size-full [&>img]:object-contain"

export const augmentSocket =
  "pointer-events-auto cursor-pointer data-popup-open:border-brand data-popup-open:shadow-[0_0_12px_color-mix(in_oklch,var(--color-brand)_45%,transparent)] data-popup-open:outline data-popup-open:outline-brand/40 data-popup-open:outline-offset-2 hover:border-brand hover:shadow-[0_0_12px_color-mix(in_oklch,var(--color-brand)_45%,transparent)] hover:outline hover:outline-brand/40 hover:outline-offset-2 focus-visible:border-brand focus-visible:shadow-[0_0_12px_color-mix(in_oklch,var(--color-brand)_45%,transparent)] focus-visible:outline focus-visible:outline-brand/40 focus-visible:outline-offset-2"

export const jewelCard =
  "popup-corners dither-fade relative isolate flex min-w-0 flex-col border border-(--inspection-border) bg-paper-deep text-ink [--equipment-modifier-font-size:14px] [--equipment-line-height:1.6] [--equipment-line-gap:3px] [--jewel-art:56px] [--jewel-inset:18px] [--inspection-accent:var(--item-color)] [--dither-color:var(--inspection-accent)] [--dither-opacity:0.07] data-[active=false]:opacity-60 [&_[data-slot=popover-title]]:font-display [&_[data-slot=popover-title]]:text-card-title [&_[data-slot=popover-title]]:leading-[1.1] [&_[data-slot=popover-title]]:font-medium [&_[data-slot=popover-title]]:text-(--inspection-accent) [&_[data-slot=jewel-art]]:absolute [&_[data-slot=jewel-art]]:top-3.5 [&_[data-slot=jewel-art]]:left-(--jewel-inset) [&_[data-slot=jewel-art]]:z-1 [&_[data-slot=jewel-art]]:pointer-events-none [&_[data-slot=jewel-art]>.item-slot]:size-(--jewel-art) [&_[data-slot=jewel-art]>.item-slot]:shrink-0 [&_[data-slot=jewel-art]>.item-slot]:p-1.5 [&_[data-slot=jewel-body]]:min-w-0 [&_[data-slot=jewel-body]]:flex-1 [&_[data-slot=jewel-body]>header]:min-h-[calc(var(--jewel-art)+28px)] [&_[data-slot=jewel-body]>header]:pt-3.5 [&_[data-slot=jewel-body]>header]:pr-12 [&_[data-slot=jewel-body]>header]:pb-3 [&_[data-slot=jewel-body]>header]:pl-[calc(var(--jewel-inset)+var(--jewel-art)+14px)] [&_[data-slot=jewel-body]>div]:px-(--jewel-inset) [&_[data-slot=jewel-body]>div]:pt-3 [&_[data-slot=jewel-body]>div]:pb-3.5"
