"""Extract class and ascendancy emblems from pinned PoB DDS arrays.

The passive tree atlases ship one 1500px "ClassesX" layer per class and
ascendancy. Each becomes a small emblem plus a tighter bust crop for avatars,
since the game data has no separate portraits. Newest tree version wins; older
versions only add names the newer ones no longer carry. Run with Pillow and
zstandard, then `bun run format`.
"""
import hashlib, io, json, pathlib, struct, urllib.request
from PIL import Image
import zstandard
ROOT = pathlib.Path(__file__).resolve().parents[1]
REVISION = "ce566eac45ea8a86477f513c7ee65a1ebe60014e"
SOURCE = f"https://raw.githubusercontent.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/{REVISION}/src/TreeData/"
SIZE = 192
PORTRAIT = 176
# The figure's head sits around 30% down every emblem; crop a square there.
PORTRAIT_CROP = (0.5, 0.30, 0.46)
BC7 = {98, 99}  # DXGI_FORMAT_BC7_UNORM, _UNORM_SRGB
dest = ROOT / "public/class-art"
dest.mkdir(parents=True, exist_ok=True)
art = {}
portraits = {}
def version_key(version):
    return tuple(int(part) for part in version.split("_"))
versions = sorted((p.stem for p in (ROOT / "public/pob-trees/v3").glob("*.json")), key=version_key, reverse=True)
for version in versions:
    data = json.load(urllib.request.urlopen(SOURCE + version + "/tree.json"))
    for file, entries in data.get("ddsCoords", {}).items():
        if not file.startswith("ascendancy-background_1500_"):
            continue
        wanted = {path[len("Classes"):]: index for path, index in entries.items() if path.startswith("Classes")}
        wanted = {name: index for name, index in wanted.items() if name not in art}
        if not wanted:
            continue
        raw = zstandard.ZstdDecompressor().decompress(urllib.request.urlopen(SOURCE + version + "/" + file).read())
        if raw[:4] != b"DDS " or raw[84:88] != b"DX10":
            raise ValueError("Unsupported atlas format")
        fmt, dimension, _, layers, _ = struct.unpack("<5I", raw[128:148])
        if fmt not in BC7 or dimension != 3:
            raise ValueError(f"Expected BC7 2D texture array, got format {fmt}")
        height, width = struct.unpack("<2I", raw[12:20])
        mip_count = struct.unpack("<I", raw[28:32])[0]
        stride = sum(max(1, ((width >> m) + 3) // 4) * max(1, ((height >> m) + 3) // 4) * 16 for m in range(mip_count))
        assert len(raw) == 148 + stride * layers, (file, len(raw), stride, layers, width, height, mip_count)
        header = bytearray(raw[:148])
        struct.pack_into("<I", header, 140, 1)
        def save(image):
            output = io.BytesIO()
            image.save(output, format="WEBP", quality=85, method=6)
            content = output.getvalue()
            file_name = hashlib.sha256(content).hexdigest()[:24] + ".webp"
            (dest / file_name).write_bytes(content)
            return "/class-art/" + file_name
        for name, index in sorted(wanted.items()):
            start = 148 + (index - 1) * stride
            image = Image.open(io.BytesIO(header + raw[start:start + stride])).convert("RGBA")
            cx, cy, size = PORTRAIT_CROP
            half = int(image.width * size / 2)
            centre = (int(image.width * cx), int(image.height * cy))
            portrait = image.crop((centre[0] - half, centre[1] - half, centre[0] + half, centre[1] + half))
            portrait.thumbnail((PORTRAIT, PORTRAIT), Image.LANCZOS)
            portraits[name] = save(portrait)
            image.thumbnail((SIZE, SIZE), Image.LANCZOS)
            art[name] = save(image)
        print(version, len(wanted), flush=True)
def entries(table):
    return "".join(f"  {json.dumps(name)}: {json.dumps(path)},\n" for name, path in sorted(table.items()))
(ROOT / "shared/class-art.ts").write_text(
    "// Generated by scripts/update-class-art.py; do not edit.\n"
    "// Class and ascendancy emblems are game artwork © Grinding Gear Games.\n"
    "/** Bust crops for avatars. */\n"
    "export const classPortraits: Record<string, string> = {\n" + entries(portraits) + "}\n"
    "/** Full circular emblems. */\n"
    "export const classArt: Record<string, string> = {\n" + entries(art) + "}\n"
)
(dest / "source.json").write_text(json.dumps({"source": SOURCE, "revision": REVISION, "artworkOwner": "Grinding Gear Games"}, indent=2) + "\n")
print(len(art), "emblems")
