/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as EconomyRouteImport } from './routes/economy'
import { Route as GemsRouteImport } from './routes/gems'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as TreesRouteImport } from './routes/trees'
import { Route as BuildBinIndexRouteImport } from './routes/build-bin.index'
import { Route as BuildBinSlugRouteImport } from './routes/build-bin.$slug'
import { Route as CurrencySlugRouteImport } from './routes/currency.$slug'
import { Route as EconomyIndexRouteImport } from './routes/economy.index'
import { Route as EconomyMarketRouteImport } from './routes/economy.market'
import { Route as EconomyMoversRouteImport } from './routes/economy.movers'
import { Route as GemsIndexRouteImport } from './routes/gems.index'
import { Route as GemsGemRouteImport } from './routes/gems.$gem'
import { Route as PatchNotesIndexRouteImport } from './routes/patch-notes.index'
import { Route as PatchNotesThreadIdRouteImport } from './routes/patch-notes.$threadId'
import { Route as TreesIndexRouteImport } from './routes/trees.index'
import { Route as TreesAscendanciesRouteImport } from './routes/trees.ascendancies'
import { Route as TreesAtlasRouteImport } from './routes/trees.atlas'
import { Route as TreesPassiveRouteImport } from './routes/trees.passive'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OgCurrencySlugRouteImport } from './routes/og.currency.$slug'
import { Route as OgGemsIndexRouteImport } from './routes/og.gems.index'
import { Route as OgGemsGemRouteImport } from './routes/og.gems.$gem'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomyRoute = EconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsRoute = GemsRouteImport.update({
  id: '/gems',
  path: '/gems',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const TreesRoute = TreesRouteImport.update({
  id: '/trees',
  path: '/trees',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildBinIndexRoute = BuildBinIndexRouteImport.update({
  id: '/build-bin/',
  path: '/build-bin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildBinSlugRoute = BuildBinSlugRouteImport.update({
  id: '/build-bin/$slug',
  path: '/build-bin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencySlugRoute = CurrencySlugRouteImport.update({
  id: '/currency/$slug',
  path: '/currency/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomyIndexRoute = EconomyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EconomyRoute,
} as any)
const EconomyMarketRoute = EconomyMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => EconomyRoute,
} as any)
const EconomyMoversRoute = EconomyMoversRouteImport.update({
  id: '/movers',
  path: '/movers',
  getParentRoute: () => EconomyRoute,
} as any)
const GemsIndexRoute = GemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GemsRoute,
} as any)
const GemsGemRoute = GemsGemRouteImport.update({
  id: '/$gem',
  path: '/$gem',
  getParentRoute: () => GemsRoute,
} as any)
const PatchNotesIndexRoute = PatchNotesIndexRouteImport.update({
  id: '/patch-notes/',
  path: '/patch-notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatchNotesThreadIdRoute = PatchNotesThreadIdRouteImport.update({
  id: '/patch-notes/$threadId',
  path: '/patch-notes/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const TreesIndexRoute = TreesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreesRoute,
} as any)
const TreesAscendanciesRoute = TreesAscendanciesRouteImport.update({
  id: '/ascendancies',
  path: '/ascendancies',
  getParentRoute: () => TreesRoute,
} as any)
const TreesAtlasRoute = TreesAtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => TreesRoute,
} as any)
const TreesPassiveRoute = TreesPassiveRouteImport.update({
  id: '/passive',
  path: '/passive',
  getParentRoute: () => TreesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OgCurrencySlugRoute = OgCurrencySlugRouteImport.update({
  id: '/og/currency/$slug',
  path: '/og/currency/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgGemsIndexRoute = OgGemsIndexRouteImport.update({
  id: '/og/gems/',
  path: '/og/gems/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgGemsGemRoute = OgGemsGemRouteImport.update({
  id: '/og/gems/$gem',
  path: '/og/gems/$gem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-account': typeof CreateAccountRoute
  '/economy': typeof EconomyRouteWithChildren
  '/gems': typeof GemsRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/trees': typeof TreesRouteWithChildren
  '/build-bin/$slug': typeof BuildBinSlugRoute
  '/currency/$slug': typeof CurrencySlugRoute
  '/economy/market': typeof EconomyMarketRoute
  '/economy/movers': typeof EconomyMoversRoute
  '/gems/$gem': typeof GemsGemRoute
  '/patch-notes/$threadId': typeof PatchNotesThreadIdRoute
  '/trees/ascendancies': typeof TreesAscendanciesRoute
  '/trees/atlas': typeof TreesAtlasRoute
  '/trees/passive': typeof TreesPassiveRoute
  '/build-bin/': typeof BuildBinIndexRoute
  '/economy/': typeof EconomyIndexRoute
  '/gems/': typeof GemsIndexRoute
  '/patch-notes/': typeof PatchNotesIndexRoute
  '/trees/': typeof TreesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/og/currency/$slug': typeof OgCurrencySlugRoute
  '/og/gems/$gem': typeof OgGemsGemRoute
  '/og/gems/': typeof OgGemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-account': typeof CreateAccountRoute
  '/methodology': typeof MethodologyRoute
  '/build-bin/$slug': typeof BuildBinSlugRoute
  '/currency/$slug': typeof CurrencySlugRoute
  '/economy/market': typeof EconomyMarketRoute
  '/economy/movers': typeof EconomyMoversRoute
  '/gems/$gem': typeof GemsGemRoute
  '/patch-notes/$threadId': typeof PatchNotesThreadIdRoute
  '/trees/ascendancies': typeof TreesAscendanciesRoute
  '/trees/atlas': typeof TreesAtlasRoute
  '/trees/passive': typeof TreesPassiveRoute
  '/build-bin': typeof BuildBinIndexRoute
  '/economy': typeof EconomyIndexRoute
  '/gems': typeof GemsIndexRoute
  '/patch-notes': typeof PatchNotesIndexRoute
  '/trees': typeof TreesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/og/currency/$slug': typeof OgCurrencySlugRoute
  '/og/gems/$gem': typeof OgGemsGemRoute
  '/og/gems': typeof OgGemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-account': typeof CreateAccountRoute
  '/economy': typeof EconomyRouteWithChildren
  '/gems': typeof GemsRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/trees': typeof TreesRouteWithChildren
  '/build-bin/$slug': typeof BuildBinSlugRoute
  '/currency/$slug': typeof CurrencySlugRoute
  '/economy/market': typeof EconomyMarketRoute
  '/economy/movers': typeof EconomyMoversRoute
  '/gems/$gem': typeof GemsGemRoute
  '/patch-notes/$threadId': typeof PatchNotesThreadIdRoute
  '/trees/ascendancies': typeof TreesAscendanciesRoute
  '/trees/atlas': typeof TreesAtlasRoute
  '/trees/passive': typeof TreesPassiveRoute
  '/build-bin/': typeof BuildBinIndexRoute
  '/economy/': typeof EconomyIndexRoute
  '/gems/': typeof GemsIndexRoute
  '/patch-notes/': typeof PatchNotesIndexRoute
  '/trees/': typeof TreesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/og/currency/$slug': typeof OgCurrencySlugRoute
  '/og/gems/$gem': typeof OgGemsGemRoute
  '/og/gems/': typeof OgGemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create-account'
    | '/economy'
    | '/gems'
    | '/methodology'
    | '/trees'
    | '/build-bin/$slug'
    | '/currency/$slug'
    | '/economy/market'
    | '/economy/movers'
    | '/gems/$gem'
    | '/patch-notes/$threadId'
    | '/trees/ascendancies'
    | '/trees/atlas'
    | '/trees/passive'
    | '/build-bin/'
    | '/economy/'
    | '/gems/'
    | '/patch-notes/'
    | '/trees/'
    | '/api/auth/$'
    | '/og/currency/$slug'
    | '/og/gems/$gem'
    | '/og/gems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create-account'
    | '/methodology'
    | '/build-bin/$slug'
    | '/currency/$slug'
    | '/economy/market'
    | '/economy/movers'
    | '/gems/$gem'
    | '/patch-notes/$threadId'
    | '/trees/ascendancies'
    | '/trees/atlas'
    | '/trees/passive'
    | '/build-bin'
    | '/economy'
    | '/gems'
    | '/patch-notes'
    | '/trees'
    | '/api/auth/$'
    | '/og/currency/$slug'
    | '/og/gems/$gem'
    | '/og/gems'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/create-account'
    | '/economy'
    | '/gems'
    | '/methodology'
    | '/trees'
    | '/build-bin/$slug'
    | '/currency/$slug'
    | '/economy/market'
    | '/economy/movers'
    | '/gems/$gem'
    | '/patch-notes/$threadId'
    | '/trees/ascendancies'
    | '/trees/atlas'
    | '/trees/passive'
    | '/build-bin/'
    | '/economy/'
    | '/gems/'
    | '/patch-notes/'
    | '/trees/'
    | '/api/auth/$'
    | '/og/currency/$slug'
    | '/og/gems/$gem'
    | '/og/gems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreateAccountRoute: typeof CreateAccountRoute
  EconomyRoute: typeof EconomyRouteWithChildren
  GemsRoute: typeof GemsRouteWithChildren
  MethodologyRoute: typeof MethodologyRoute
  TreesRoute: typeof TreesRouteWithChildren
  BuildBinSlugRoute: typeof BuildBinSlugRoute
  CurrencySlugRoute: typeof CurrencySlugRoute
  PatchNotesThreadIdRoute: typeof PatchNotesThreadIdRoute
  BuildBinIndexRoute: typeof BuildBinIndexRoute
  PatchNotesIndexRoute: typeof PatchNotesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OgCurrencySlugRoute: typeof OgCurrencySlugRoute
  OgGemsGemRoute: typeof OgGemsGemRoute
  OgGemsIndexRoute: typeof OgGemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economy': {
      id: '/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof EconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems': {
      id: '/gems'
      path: '/gems'
      fullPath: '/gems'
      preLoaderRoute: typeof GemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trees': {
      id: '/trees'
      path: '/trees'
      fullPath: '/trees'
      preLoaderRoute: typeof TreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-bin/': {
      id: '/build-bin/'
      path: '/build-bin'
      fullPath: '/build-bin/'
      preLoaderRoute: typeof BuildBinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-bin/$slug': {
      id: '/build-bin/$slug'
      path: '/build-bin/$slug'
      fullPath: '/build-bin/$slug'
      preLoaderRoute: typeof BuildBinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency/$slug': {
      id: '/currency/$slug'
      path: '/currency/$slug'
      fullPath: '/currency/$slug'
      preLoaderRoute: typeof CurrencySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economy/': {
      id: '/economy/'
      path: '/'
      fullPath: '/economy/'
      preLoaderRoute: typeof EconomyIndexRouteImport
      parentRoute: typeof EconomyRoute
    }
    '/economy/market': {
      id: '/economy/market'
      path: '/market'
      fullPath: '/economy/market'
      preLoaderRoute: typeof EconomyMarketRouteImport
      parentRoute: typeof EconomyRoute
    }
    '/economy/movers': {
      id: '/economy/movers'
      path: '/movers'
      fullPath: '/economy/movers'
      preLoaderRoute: typeof EconomyMoversRouteImport
      parentRoute: typeof EconomyRoute
    }
    '/gems/': {
      id: '/gems/'
      path: '/'
      fullPath: '/gems/'
      preLoaderRoute: typeof GemsIndexRouteImport
      parentRoute: typeof GemsRoute
    }
    '/gems/$gem': {
      id: '/gems/$gem'
      path: '/$gem'
      fullPath: '/gems/$gem'
      preLoaderRoute: typeof GemsGemRouteImport
      parentRoute: typeof GemsRoute
    }
    '/patch-notes/': {
      id: '/patch-notes/'
      path: '/patch-notes'
      fullPath: '/patch-notes/'
      preLoaderRoute: typeof PatchNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patch-notes/$threadId': {
      id: '/patch-notes/$threadId'
      path: '/patch-notes/$threadId'
      fullPath: '/patch-notes/$threadId'
      preLoaderRoute: typeof PatchNotesThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trees/': {
      id: '/trees/'
      path: '/'
      fullPath: '/trees/'
      preLoaderRoute: typeof TreesIndexRouteImport
      parentRoute: typeof TreesRoute
    }
    '/trees/ascendancies': {
      id: '/trees/ascendancies'
      path: '/ascendancies'
      fullPath: '/trees/ascendancies'
      preLoaderRoute: typeof TreesAscendanciesRouteImport
      parentRoute: typeof TreesRoute
    }
    '/trees/atlas': {
      id: '/trees/atlas'
      path: '/atlas'
      fullPath: '/trees/atlas'
      preLoaderRoute: typeof TreesAtlasRouteImport
      parentRoute: typeof TreesRoute
    }
    '/trees/passive': {
      id: '/trees/passive'
      path: '/passive'
      fullPath: '/trees/passive'
      preLoaderRoute: typeof TreesPassiveRouteImport
      parentRoute: typeof TreesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/currency/$slug': {
      id: '/og/currency/$slug'
      path: '/og/currency/$slug'
      fullPath: '/og/currency/$slug'
      preLoaderRoute: typeof OgCurrencySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/gems/': {
      id: '/og/gems/'
      path: '/og/gems'
      fullPath: '/og/gems/'
      preLoaderRoute: typeof OgGemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/gems/$gem': {
      id: '/og/gems/$gem'
      path: '/og/gems/$gem'
      fullPath: '/og/gems/$gem'
      preLoaderRoute: typeof OgGemsGemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EconomyRouteChildren {
  EconomyMarketRoute: typeof EconomyMarketRoute
  EconomyMoversRoute: typeof EconomyMoversRoute
  EconomyIndexRoute: typeof EconomyIndexRoute
}

const EconomyRouteChildren: EconomyRouteChildren = {
  EconomyMarketRoute: EconomyMarketRoute,
  EconomyMoversRoute: EconomyMoversRoute,
  EconomyIndexRoute: EconomyIndexRoute,
}

const EconomyRouteWithChildren =
  EconomyRoute._addFileChildren(EconomyRouteChildren)

interface GemsRouteChildren {
  GemsGemRoute: typeof GemsGemRoute
  GemsIndexRoute: typeof GemsIndexRoute
}

const GemsRouteChildren: GemsRouteChildren = {
  GemsGemRoute: GemsGemRoute,
  GemsIndexRoute: GemsIndexRoute,
}

const GemsRouteWithChildren = GemsRoute._addFileChildren(GemsRouteChildren)

interface TreesRouteChildren {
  TreesAscendanciesRoute: typeof TreesAscendanciesRoute
  TreesAtlasRoute: typeof TreesAtlasRoute
  TreesPassiveRoute: typeof TreesPassiveRoute
  TreesIndexRoute: typeof TreesIndexRoute
}

const TreesRouteChildren: TreesRouteChildren = {
  TreesAscendanciesRoute: TreesAscendanciesRoute,
  TreesAtlasRoute: TreesAtlasRoute,
  TreesPassiveRoute: TreesPassiveRoute,
  TreesIndexRoute: TreesIndexRoute,
}

const TreesRouteWithChildren = TreesRoute._addFileChildren(TreesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreateAccountRoute: CreateAccountRoute,
  EconomyRoute: EconomyRouteWithChildren,
  GemsRoute: GemsRouteWithChildren,
  MethodologyRoute: MethodologyRoute,
  TreesRoute: TreesRouteWithChildren,
  BuildBinSlugRoute: BuildBinSlugRoute,
  CurrencySlugRoute: CurrencySlugRoute,
  PatchNotesThreadIdRoute: PatchNotesThreadIdRoute,
  BuildBinIndexRoute: BuildBinIndexRoute,
  PatchNotesIndexRoute: PatchNotesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OgCurrencySlugRoute: OgCurrencySlugRoute,
  OgGemsGemRoute: OgGemsGemRoute,
  OgGemsIndexRoute: OgGemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
